# Generated by Django 5.1.6 on 2025-02-25 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_number', models.CharField(max_length=20, unique=True)),
                ('owner', models.CharField(max_length=100)),
                ('insured', models.BooleanField(default=False)),
            ],
        ),
    ]
