# Generated by Django 5.1.6 on 2025-02-25 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0001_initial'),
    ]

    operations = [
        # These operations were already applied in 0002_alter_vehicle_options_and_more
    ]
