# Generated by Django 5.1.7 on 2026-04-08 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0002_alter_vehicle_options_and_more'),
        ('scanner', '0002_rename_insured_vehicle_is_insured_and_more'),
    ]

    operations = [
    ]
